id = "forest-night"
name = "Forest Night Theme"
description = "Forest Night is a green based color scheme; it's designed to be warm and soft in order to protect developers' eyes"
version = "0.1.0"
schema_version = 1
authors = ["Evgenii Gorodilov <jarith@fastmail.de>"]
repository = "https://github.com/jarith/forest-night-zed"
